title: Jerry Nissan Antony Marcelin # your name (or website title) here
logo: "/jerry01.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Cyber Security Consultant
  <br><br>
  <a href="mailto:ajerrynissan@gmail.com">ajerrynissan@gmail.com </a>
  <br>
  <a href=“tel:+919488858776”>Call me at +91 9488858776</a>
  <br>
  <a href="https://www.linkedin.com/in/jerry-nissan-antony-marcelin-36b02991/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/jerrynissan">Gihub</a> 
theme: jekyll-theme-minimal
